export const PRODUCTS_ACTION_TYPES = {
    FETCH_PRODUCTS_START: "products/FETCH_PRODUCTS_START",
    FETCH_PRODUCTS_SUCCESS: "products/FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILED: "products/FETCH_PRODUCTS_FAILED",
    SORT_PRODUCTS_BY_PRICE: "products/SORT_PRODUCTS_BY_PRICE",
    UNSORT_PRODUCTS: "products/UNSORT_PRODUCTS",
    EDIT_PRODUCTS: "products/EDIT_PRODUCTS",
    DELETE_PRODUCT: "product/DELETE_PRODUCT",
    ADD_PRODUCT: "product/ADD_PRODUCT",
  };